
import React, { useState, useEffect } from 'react';
import { Copy, Check, Calendar, RotateCcw, ArrowRightLeft, Search, Info } from 'lucide-react';
import ToolLayout from '../ui/ToolLayout';
import { Button } from '../ui/Button';
import { Input } from '../ui/Input';
import { Card, CardContent } from '../ui/Card';
import { cn } from '@/lib/utils';

const ThaiDateConverter: React.FC = () => {
  const [date, setDate] = useState(new Date().toISOString().split('T')[0]);
  const [parseInput, setParseInput] = useState('');
  const [parseResult, setParseResult] = useState<{ iso: string; formatted: string } | null>(null);
  const [copiedId, setCopiedId] = useState<string | null>(null);

  const thaiMonths = [
    'มกราคม', 'กุมภาพันธ์', 'มีนาคม', 'เมษายน', 'พฤษภาคม', 'มิถุนายน',
    'กรกฎาคม', 'สิงหาคม', 'กันยายน', 'ตุลาคม', 'พฤศจิกายน', 'ธันวาคม'
  ];

  const thaiShortMonths = [
    'ม.ค.', 'ก.พ.', 'มี.ค.', 'เม.ย.', 'พ.ค.', 'มิ.ย.',
    'ก.ค.', 'ส.ค.', 'ก.ย.', 'ต.ค.', 'พ.ย.', 'ธ.ค.'
  ];

  const thaiDays = [
    'อาทิตย์', 'จันทร์', 'อังคาร', 'พุธ', 'พฤหัสบดี', 'ศุกร์', 'เสาร์'
  ];

  const toThaiDigits = (num: number | string) => {
    const digits = ['๐', '๑', '๒', '๓', '๔', '๕', '๖', '๗', '๘', '๙'];
    return num.toString().split('').map(d => isNaN(parseInt(d)) ? d : digits[parseInt(d)]).join('');
  };

  useEffect(() => {
    if (!parseInput.trim()) {
      setParseResult(null);
      return;
    }

    const input = parseInput.trim();
    const parts = input.split(/[\s/.-]+/); 
    
    let day: number | null = null;
    let month: number | null = null;
    let year: number | null = null;

    for (const part of parts) {
      const fullMonthIdx = thaiMonths.findIndex(m => m === part);
      if (fullMonthIdx !== -1) {
        month = fullMonthIdx;
        continue;
      }
      
      const shortMonthIdx = thaiShortMonths.findIndex(m => m === part || m === part + '.');
      if (shortMonthIdx !== -1) {
        month = shortMonthIdx;
        continue;
      }

      const num = parseInt(part.replace(/[๐-๙]/g, d => '๐๑๒๓๔๕๖๗๘๙'.indexOf(d).toString()));
      if (!isNaN(num)) {
        if (num > 2500 || (num > 100 && num < 2500)) {
          year = num;
        } else if (num > 0 && num <= 31 && day === null) {
          day = num;
        } else if (num > 0 && num <= 12 && month === null) {
          month = num - 1;
        } else if (year === null) {
          year = num;
        }
      }
    }

    if (day !== null && month !== null && year !== null) {
      const adYear = year > 2400 ? year - 543 : year;
      const d = new Date(adYear, month, day);
      
      if (!isNaN(d.getTime())) {
        setParseResult({
          iso: d.toISOString().split('T')[0],
          formatted: d.toLocaleDateString('en-CA') 
        });
      } else {
        setParseResult(null);
      }
    } else {
      setParseResult(null);
    }
  }, [parseInput]);

  const getFormats = () => {
    const d = new Date(date);
    if (isNaN(d.getTime())) return [];

    const day = d.getDate();
    const monthIndex = d.getMonth();
    const yearBE = d.getFullYear() + 543;
    const dayOfWeek = d.getDay();

    return [
      {
        id: 'full',
        label: 'Full Thai Date (ทางการ)',
        value: `วัน${thaiDays[dayOfWeek]}ที่ ${day} ${thaiMonths[monthIndex]} พ.ศ. ${yearBE}`,
        tooltip: 'Used for official certificates, formal documents, and government letters.'
      },
      {
        id: 'short',
        label: 'Short Thai Date (ย่อ)',
        value: `${day} ${thaiShortMonths[monthIndex]} ${yearBE.toString().slice(-2)}`,
        tooltip: 'Compact format suitable for mobile apps, internal notes, or limited space UIs.'
      },
      {
        id: 'thai-digits',
        label: 'Official Format (เลขไทย)',
        value: `${toThaiDigits(day)} ${thaiMonths[monthIndex]} พุทธศักราช ${toThaiDigits(yearBE)}`,
        tooltip: 'Traditional and legal format often required in high-level government or ceremonial contexts.'
      },
      {
        id: 'iso-be',
        label: 'ISO BE (YYYY-MM-DD)',
        value: `${yearBE}-${(monthIndex + 1).toString().padStart(2, '0')}-${day.toString().padStart(2, '0')}`,
        tooltip: 'Database storage format using the Buddhist Era year, common in legacy Thai enterprise systems.'
      },
      {
        id: 'timestamp',
        label: 'Unix Timestamp',
        value: Math.floor(d.getTime() / 1000).toString(),
        tooltip: 'Standard Unix Epoch time (seconds). Critical for backend logic and cross-system synchronization.'
      },
      {
        id: 'js-date',
        label: 'Thai Locale String',
        value: d.toLocaleDateString('th-TH', { year: 'numeric', month: 'long', day: 'numeric' }),
        tooltip: 'Default string generated by browser-native toLocaleDateString("th-TH") method.'
      }
    ];
  };

  const formats = getFormats();

  const handleCopy = (val: string, id: string) => {
    navigator.clipboard.writeText(val);
    setCopiedId(id);
    setTimeout(() => setCopiedId(null), 2000);
  };

  const resetToday = () => {
    setDate(new Date().toISOString().split('T')[0]);
  };

  return (
    <ToolLayout>
      <ToolLayout.Section title="Reverse Parser (Thai String → ISO)">
        <Card className="border-dashed border-primary/20 bg-primary/5">
          <CardContent className="p-6 grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="space-y-2">
                <label className="text-[10px] font-bold text-muted-foreground uppercase tracking-wider">Input Thai Date String</label>
                <div className="relative">
                <Input
                    type="text"
                    value={parseInput}
                    onChange={(e) => setParseInput(e.target.value)}
                    placeholder="เช่น 16 กุมภาพันธ์ 2569"
                    className="pl-10"
                />
                <Search className="w-4 h-4 text-muted-foreground absolute left-3 top-1/2 -translate-y-1/2" />
                </div>
            </div>

            <div className="space-y-2">
                <label className="text-[10px] font-bold text-muted-foreground uppercase tracking-wider">Converted ISO Date</label>
                <div className={cn("w-full h-10 border rounded-md px-3 flex items-center justify-between transition-all",
                    parseResult 
                        ? "border-green-500/50 bg-green-500/10"
                        : "border-border bg-muted/50 opacity-50"
                )}>
                <div className="font-mono text-sm text-primary">
                    {parseResult ? parseResult.formatted : 'Waiting for input...'}
                </div>
                {parseResult && (
                    <Button
                        variant="ghost"
                        size="icon"
                        onClick={() => handleCopy(parseResult.formatted, 'parsed-result')}
                        className={cn("h-7 w-7", copiedId === 'parsed-result' ? "text-green-600" : "text-muted-foreground hover:text-foreground")}
                    >
                    {copiedId === 'parsed-result' ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
                    </Button>
                )}
                </div>
            </div>
          </CardContent>
        </Card>
      </ToolLayout.Section>

      <ToolLayout.Section 
        title="Forward Converter"
        actions={
            <Button
                variant="ghost"
                size="sm"
                onClick={resetToday}
                className="text-xs text-primary hover:text-primary/80 hover:bg-primary/10"
            >
                <RotateCcw className="w-3.5 h-3.5 mr-2" /> Today
            </Button>
        }
      >
         <div className="p-6 bg-card">
            <div className="mb-6">
                 <Input
                    type="date"
                    value={date}
                    onChange={(e) => setDate(e.target.value)}
                    className="w-full"
                  />
            </div>
          
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {formats.map((f) => (
                <Card key={f.id} className="group hover:border-primary/50 transition-all">
                    <CardContent className="p-4 space-y-3">
                        <div className="flex items-center justify-between">
                            <div className="flex items-center gap-2">
                                <span className="text-[10px] font-bold text-muted-foreground uppercase tracking-widest">{f.label}</span>
                                <div className="relative group/tooltip">
                                <Info className="w-3 h-3 text-muted-foreground cursor-help" />
                                <div className="absolute bottom-full left-0 mb-2 hidden group-hover/tooltip:block w-48 p-2 bg-popover text-[10px] text-popover-foreground rounded border border-border shadow-xl z-50 pointer-events-none">
                                    <p className="font-semibold text-primary mb-1">Usage:</p>
                                    {f.tooltip}
                                </div>
                                </div>
                            </div>
                            <Button
                                variant="ghost"
                                size="icon"
                                onClick={() => handleCopy(String(f.value), f.id)}
                                className={cn("h-6 w-6",
                                copiedId === f.id ? "text-green-600" : "text-muted-foreground hover:text-foreground"
                                )}
                            >
                                {copiedId === f.id ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
                            </Button>
                        </div>
                        <div className="font-mono text-sm text-primary break-all bg-muted/50 p-2 rounded border border-border">
                            {f.value}
                        </div>
                    </CardContent>
                </Card>
                ))}
            </div>
         </div>
      </ToolLayout.Section>
    </ToolLayout>
  );
};

export default ThaiDateConverter;
